### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by ptn** [FiloSottile/alum#5]
Our page https://alum.hackerschool.com/ is erroring out with a 500. I digged into the logs and found this:

```
x509: certificate signed by unknown authority
(possibly because of "x509: cannot verify signature: algorithm unimplemented"
while trying to verify candidate authority certificate
"COMODO RSA Certification Authority")
```

but I have no idea what to make of it, and Google didn't help much. halp @FiloSottile @marksamman

**Comment by FiloSottile** [comment]
I'm confused, it works fine for me. It used to spew that error a couple of weeks ago because of a SHA256 cert in the API https chain, but rebuilding the binary with a recent Go fixed the issue.

Can you help me reproduce?

**Comment by ptn** [comment]
Oh lord, nvm, I tried a couple of times and got a blank page, but I just tried again and it's working fine now. I blame hotel wifi.

So if that error is not gonna happen again then let's just close this =D

**Comment by FiloSottile** [comment]
Hotel Wi-Fi is the root of all evils, always said that!
